# Generated by Django 4.2.18 on 2025-01-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='ConPassword',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='UserName',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
