# Generated by Django 3.2.25 on 2025-02-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('warranty_status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Not Available', 'Not Available')], max_length=20)),
            ],
        ),
    ]
