# Generated by Django 4.2.19 on 2025-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_customuser_name_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Agent', 'Agent')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
