# Generated by Django 5.1.5 on 2025-02-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_productregistration'),
        ('login', '0003_customuser_user_type'),
    ]

    operations = [
    ]
