# Generated by Django 3.2.25 on 2025-02-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_productregistration'),
        ('login', '0003_customuser_user_type'),
    ]

    operations = [
    ]
